/**
 * The M9 cold-start demo: a topic never indexed before, taken end to end.
 *
 * In:  a topic string (default: one from a field unrelated to both eval topics).
 * Out: examples/cold_start.md — the transcript, plus every tool call the agent made.
 * Runs against a scratch config pointing at data_demo/, so the eval corpus in data/ and
 * the M8 numbers measured against it are left untouched.
 */

import { existsSync, mkdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { parseArgs } from "node:util";

import { PythonBridge } from "../app/bridge/client.js";
import {
  isToolError, type AskFailure, type AskResult, type EnginePaths, type IndexResult, type JsonObject,
  type ToolError, type TraceRecord,
} from "../app/bridge/types.js";
import { REPO_ROOT } from "../app/paths.js";
import { evidencePath } from "../eval/lib.js";
import { errorMessage } from "./lib.js";

const DEMO_ROOT = "data_demo";
const DEFAULT_TOPIC = "protein structure prediction with deep learning";
// No explicit categories: the query planner picks its own and folds them into the query
// (arxiv_query.apply_categories, called at plan time). Passing more here would AND a
// second filter onto that one and narrow the search twice. Letting the planner choose is
// also the more honest demo — nothing is hand-tuned for this topic.

// Two questions: one the fresh corpus should answer, one it cannot. The second is the
// point of the demo as much as the first — a system that answers everything has not
// demonstrated abstention.
const ANSWERABLE = "What model architectures do these papers use to predict protein structure, and what do they report about accuracy?";
const UNANSWERABLE = "What do these papers say about sourdough fermentation temperature and starter culture biology?";

class DemoAbort extends Error {}

interface Indexing {
  stdout: string;
  papers: number;
  chunks: number;
  figures: number;
  vectors: number;
  arxiv_query: string | undefined;
  elapsed_s: number;
}

interface DemoRun {
  label: string;
  question: string;
  answer: string;
  trace: TraceRecord[];
  iterations: number;
  tool_calls: number;
  context_tokens: number;
  stopped_because: string;
  elapsed_s: number;
}

/**
 * A config identical to the project's but rooted at data_demo/.
 *
 * Written through the YAML (by the bridge, which owns the parser) rather than poked into a
 * loaded Config: config sections are read-only by design, and the demo should exercise the
 * same load path the CLI uses.
 */
async function scratchConfig(fresh: boolean): Promise<string> {
  const demoDir = join(REPO_ROOT, DEMO_ROOT);
  if (fresh && existsSync(demoDir)) rmSync(demoDir, { recursive: true, force: true });
  mkdirSync(demoDir, { recursive: true });

  const writer = new PythonBridge();
  try {
    const { path } = await writer.call<{ path: string }>("write_scratch_config", {
      out: join(demoDir, "config.yaml"),
      // arXiv answers 429 and 503 intermittently under load, and one failed search costs
      // the whole demo (~20 minutes of downloads, vision calls and two agent runs). A
      // slightly wider retry budget and a wider gap than the project default is about
      // surviving a flaky feed without leaning on it: retries are few, and the client
      // leaves 6s between requests rather than the 4s used for ordinary indexing.
      section_updates: { collection: { max_retries: 4, request_delay_s: 6 } },
      section_replacements: {
        paths: {
          data_dir: DEMO_ROOT,
          papers_dir: `${DEMO_ROOT}/papers`,
          index_dir: `${DEMO_ROOT}/index`,
          cache_dir: `${DEMO_ROOT}/cache`,
          logs_dir: `${DEMO_ROOT}/logs`,
          prompts_dir: "src/prompts",
        },
      },
    });
    return path;
  } finally {
    await writer.close();
  }
}

/** A demo that starts with papers already indexed is not a cold start. */
function assertCold(paths: EnginePaths): void {
  if (existsSync(paths.chunks) && statSync(paths.chunks).size > 0) {
    throw new DemoAbort(`${paths.chunks} is not empty — this would not be a cold start. Re-run with --fresh.`);
  }
}

/** The transcript, as markdown. */
function render(topic: string, indexing: Indexing, runs: DemoRun[]): string {
  const cli = `npx tsx app/cli.ts --config ${DEMO_ROOT}/config.yaml`;
  const lines = [
    "# Cold-start demo",
    "",
    "A topic the system had never seen, taken from nothing to an answered question. "
    + `Generated by \`scripts/m9_cold_start.ts\`; corpus in \`${DEMO_ROOT}/\`, separate from `
    + "the eval corpus in `data/`.",
    "",
    `**Topic:** \`${topic}\`  `,
    `**Date:** ${new Date().toLocaleDateString("en-CA")}  `,
    "**Starting state:** no papers, no chunks, no index",
    "",
    "## 1. Indexing",
    "",
    "```",
    `$ ${cli} index "${topic}"`,
    indexing.stdout.trimEnd(),
    "```",
    "",
    `arXiv query the planner produced: \`${indexing.arxiv_query ?? "n/a"}\``,
    "",
    `Papers: ${indexing.papers} · chunks: ${indexing.chunks} · figures: ${indexing.figures} · `
    + `vectors: ${indexing.vectors} · wall clock: ${indexing.elapsed_s.toFixed(0)}s`,
    "",
  ];
  runs.forEach((run, index) => {
    lines.push(
      `## ${index + 2}. ${run.label}`,
      "",
      "```",
      `$ ${cli} ask "${run.question}"`,
      "```",
      "",
      "**Tool calls**",
      "",
      "```",
    );
    for (const record of run.trace) {
      const returned = record.error || `${(record.chunk_ids_returned ?? []).length} chunk(s)`;
      const args = JSON.stringify(record.args ?? null);
      lines.push(`[${record.iteration}] ${record.tool_name}(${args.slice(0, 110)}) -> ${returned}, ${record.latency_ms}ms`);
    }
    lines.push(
      "```",
      "",
      "**Answer**",
      "",
      run.answer.trim(),
      "",
      `*${run.iterations} iteration(s), ${run.tool_calls} tool call(s), ${run.context_tokens} context tokens, `
      + `stopped: ${run.stopped_because}, ${run.elapsed_s.toFixed(0)}s*`,
      "",
    );
  });
  return lines.join("\n");
}

async function indexTopic(bridge: PythonBridge, topic: string, maxResults: number): Promise<Indexing> {
  const started = performance.now();
  const stdout: string[] = [];
  const say = (line: string): void => {
    console.log(line);
    stdout.push(line);
  };

  const result = await bridge.call<IndexResult | (ToolError & { stage?: string })>(
    "index",
    { topic, max_results: maxResults, no_describe: false },
    (event) => {
      if (event.kind === "stage") {
        const label = {
          collect: `searching arXiv for '${topic}'`,
          ingest: "extracting text and figures",
          index: "embedding and indexing",
        }[String(event.stage)];
        say(`[${event.step}/${event.of}] ${label} ...`);
      } else if (event.kind === "collected") {
        const c = event.result as JsonObject;
        say(`      ${(c.papers_added as unknown[] | undefined)?.length ?? 0} added, `
          + `${Number(c.papers_skipped ?? 0)} already held, tag '${String(c.topic_tag)}'`);
      } else if (event.kind === "ingested") {
        const i = event.result as JsonObject;
        say(`      ${Number(i.chunks_total ?? 0)} chunks, ${Number(i.figures_total ?? 0)} figures`);
      }
    },
  );
  if (isToolError(result)) {
    throw new DemoAbort(`${result.stage ?? "indexing"} failed: ${JSON.stringify(result)}`);
  }
  if (result.rate_limited) {
    // A partial collection is not the cold start this transcript claims to show.
    throw new DemoAbort("collection failed: arXiv rate-limited the search partway; re-run once it lifts");
  }
  const indexed = result.indexed;
  say(`      ${Number(indexed.chunks_indexed ?? 0)} embedded, ${Number(indexed.cache_hits ?? 0)} cache hit(s), `
    + `${Number(indexed.total_indexed ?? 0)} vectors in the index`);

  return {
    stdout: stdout.join("\n"),
    papers: (result.collected.papers_added as unknown[] | undefined)?.length ?? 0,
    chunks: Number(result.ingested.chunks_total ?? 0),
    figures: Number(result.ingested.figures_total ?? 0),
    vectors: Number(indexed.total_indexed ?? 0),
    arxiv_query: result.collected.arxiv_query as string | undefined,
    elapsed_s: (performance.now() - started) / 1000,
  };
}

async function run(bridge: PythonBridge, topic: string, maxResults: number, out: string, overwrite: boolean): Promise<number> {
  const paths = await bridge.call<EnginePaths>("paths");
  assertCold(paths);
  console.log(`cold start in ${paths.data_dir}`);

  const indexing = await indexTopic(bridge, topic, maxResults);

  const runs: DemoRun[] = [];
  for (const [label, question] of [
    ["A question the fresh corpus can answer", ANSWERABLE],
    ["A question it cannot — the abstention case", UNANSWERABLE],
  ] as const) {
    console.log(`\n--- ${label}\n${question}`);
    const began = performance.now();
    const result = await bridge.call<AskResult | AskFailure>("ask", { question, events: false });
    if (isToolError(result)) throw new DemoAbort(`agent loop failed: ${result.error} — ${result.detail}`);
    const answered = result as AskResult;
    console.log(answered.answer);
    runs.push({
      label,
      question,
      answer: answered.answer,
      trace: answered.trace_records,
      iterations: answered.iterations,
      tool_calls: answered.tool_calls,
      context_tokens: answered.context_tokens,
      stopped_because: answered.stopped_because,
      elapsed_s: (performance.now() - began) / 1000,
    });
  }

  const target = evidencePath(resolve(REPO_ROOT, out), overwrite);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, render(topic, indexing, runs), "utf-8");
  console.log(`\ntranscript written to ${target}`);
  return 0;
}

async function main(): Promise<void> {
  const { values } = parseArgs({
    options: {
      topic: { type: "string", default: DEFAULT_TOPIC },
      // Kept small because every figure costs a vision call.
      "max-results": { type: "string", default: "3" },
      fresh: { type: "boolean", default: false },
      out: { type: "string", default: "examples/cold_start.md" },
      overwrite: { type: "boolean", default: false },
    },
  });
  let bridge: PythonBridge | undefined;
  try {
    const configPath = await scratchConfig(Boolean(values.fresh));
    bridge = new PythonBridge({ configPath });
    process.exitCode = await run(bridge, String(values.topic), Number.parseInt(String(values["max-results"]), 10),
      String(values.out), Boolean(values.overwrite));
  } catch (error) {
    process.stderr.write(`${errorMessage(error)}\n`);
    process.exitCode = 1;
  } finally {
    await bridge?.close();
  }
}

void main();
