/**
 * Renders examples/worked_examples.md from the saved M8 eval results.
 *
 * In:  eval/results/{tuning_split,held_out_split}.json and eval/questions.json (read
 *      directly; older results carry Python's bare NaN, which reads as null).
 * Out: a markdown file of real, already-scored runs — an abstention, a conflicting-evidence
 *      case, and a straightforward one. Generated rather than transcribed so the answers
 *      and metrics cannot drift apart from the JSON that scored them.
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { REPO_ROOT } from "../app/paths.js";
import { errorMessage, readJson } from "./lib.js";

// [question_id, heading, why this example is here]
const PICKS: [string, string, string][] = [
  ["ni01", "Abstention — a question the corpus cannot answer",
    "The corpus holds machine-learning papers. This question is about sourdough. An "
    + "honest \"I don't have evidence for this\" is the correct answer, and a "
    + "plausible-sounding one built on weak retrieval would be a failure even if it "
    + "happened to be true."],
  ["cf01", "Conflicting evidence — the sources disagree",
    "The agent is required to surface a disagreement rather than pick the more "
    + "convincing side or average it away. Note that it also explains *why* the sources "
    + "differ, which is the part that makes the conflict useful rather than confusing."],
  ["mp01", "Multi-paper synthesis — the ordinary case",
    "Included for contrast: what a normal, well-evidenced answer looks like."],
];

type Row = Record<string, unknown> & {
  question: string;
  category: string;
  split: string;
  tools: { used: string[]; expected: string[]; missing?: string[]; unexpected?: string[] };
  citations: { resolved: number; total: number };
  fact_coverage: number | null;
  answer: string;
  iterations: number;
  tool_calls: number;
  elapsed_ms: number;
  abstained: boolean;
  expect_abstention: boolean;
};

function load(): Map<string, Row> {
  const questions = new Map(
    readJson<{ questions: Record<string, unknown>[] }>(join(REPO_ROOT, "eval", "questions.json"))
      .questions.map((q) => [String(q.question_id), q]),
  );
  const rows = new Map<string, Record<string, unknown>>();
  for (const split of ["tuning_split", "held_out_split"]) {
    const path = join(REPO_ROOT, "eval", "results", `${split}.json`);
    if (!existsSync(path)) continue;
    for (const row of readJson<{ rows: Record<string, unknown>[] }>(path).rows) {
      rows.set(String(row.question_id), { ...row, split });
    }
  }
  const out = new Map<string, Row>();
  for (const [qid, row] of rows) {
    const question = questions.get(qid);
    if (question) out.set(qid, { ...question, ...row } as Row);
  }
  return out;
}

function render(records: Map<string, Row>): string {
  const lines = [
    "# Worked examples",
    "",
    "Real runs against the 11-paper eval corpus, lifted from the scored M8 results in "
    + "`eval/results/` — not re-run for this document, so every answer here is one the "
    + "eval harness actually graded. Generated by `scripts/m9_examples.ts`.",
    "",
    "See `docs/EVALUATION.md` for the corpus these ran against and the full metrics. "
    + "For a topic taken from nothing to an answered question, see "
    + "`examples/cold_start.md`.",
    "",
  ];
  PICKS.forEach(([qid, heading, why], index) => {
    const record = records.get(qid);
    if (!record) return;
    lines.push(
      `## ${index + 1}. ${heading}`,
      "",
      `> **${record.question}**`,
      "",
      `*${why}*`,
      "",
      `\`${qid}\` · category \`${record.category}\` · ${record.split.replaceAll("_", " ")}`,
      "",
      "**Tools the agent chose**",
      "",
      "```",
      `used:     ${record.tools.used.join(" -> ") || "(none)"}`,
      `expected: ${record.tools.expected.join(", ") || "(none)"}`,
    );
    if (record.tools.missing?.length) lines.push(`missing:  ${record.tools.missing.join(", ")}`);
    if (record.tools.unexpected?.length) lines.push(`extra:    ${record.tools.unexpected.join(", ")}`);
    const coverage = record.fact_coverage;
    // NaN in the Python-era files, null in the TypeScript ones: both mean "not scored".
    const coverageText = typeof coverage !== "number" || Number.isNaN(coverage) ? "n/a (abstention)" : coverage.toFixed(2);
    lines.push(
      "```",
      "",
      "**Answer**",
      "",
      record.answer.trim(),
      "",
      `*${record.iterations} iteration(s), ${record.tool_calls} tool call(s), `
      + `${(record.elapsed_ms / 1000).toFixed(0)}s · fact coverage ${coverageText} · `
      + `citations ${record.citations.resolved}/${record.citations.total} resolved · `
      + `abstained: ${String(record.abstained)} (expected: ${String(record.expect_abstention)})*`,
      "",
    );
  });
  return lines.join("\n");
}

function main(): void {
  try {
    const out = join(REPO_ROOT, "examples", "worked_examples.md");
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, render(load()), "utf-8");
    console.log(`written to ${out}`);
    process.exitCode = 0;
  } catch (error) {
    process.stderr.write(`${errorMessage(error)}\n`);
    process.exitCode = 1;
  }
}

main();
